// data of parties
final Map<String, String> parties = {
  'AAP': 'assets/parties/AAP.jpeg',
  'AIADMK': 'assets/parties/AIADMK.jpeg',
  'AIMIM': 'assets/parties/AIMIM.png',
  'BJD': 'assets/parties/BJD.jpeg',
  'BJP': 'assets/parties/BJP.jpeg',
  'BRS': 'assets/parties/BRS.jpeg',
  'BSP': 'assets/parties/BSP.jpeg',
  'CPI': 'assets/parties/CPI.jpeg',
  'CPI(M)': 'assets/parties/CPI(M).jpeg',
  'DMK': 'assets/parties/DMK.jpeg',
  'INC': 'assets/parties/INC.jpeg',
  'Jan Sena': 'assets/parties/Jan Sena.jpeg',
  'JDU': 'assets/parties/JDU.jpeg',
  'NC': 'assets/parties/NC.jpeg',
  'NPP': 'assets/parties/NPP.jpeg',
  'PDP': 'assets/parties/PDP.jpeg',
  'RJD': 'assets/parties/RJD.jpeg',
  'Shiv Sena': 'assets/parties/Shiv Sena.jpeg',
  'Shiv Sena(U)': 'assets/parties/Shiv Sena(U).jpeg',
  'SP': 'assets/parties/SP.jpeg',
  'TDP': 'assets/parties/TDP.jpeg',
  'TMC': 'assets/parties/TMC.jpeg',
  'YSRCP': 'assets/parties/YSRCP.jpeg',
};
